kind: pipeline
type: docker
name: autofixture.js

steps:
  - name: npm install
    image: node:lts-alpine
    commands:
      - yarn
  - name: lint
    image: node:lts-alpine
    commands:
      - yarn lint
  - name: test
    image: node:lts-alpine
    commands:
      - yarn test
  - name: build
    image: node:lts-alpine
    commands:
      - yarn build
