kind: pipeline
type: docker
name: autofixture.js

steps:
  - name: npm install
    image: node:lts-alpine
    commands:
      - npm ci
  - name: lint
    image: node:lts-alpine
    commands:
      - npm run lint
  - name: test
    image: node:lts-alpine
    commands:
      - npm run lint
  - name: build
    image: node:lts-alpine
    commands:
      - npm run build
